apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-terraform-syntax

spec:
  params:
    - name: IMAGE_URL
      type: string
    - name: IMAGE_DIGEST
      type: string

  steps:
    - name: test-terraform-syntax
      #image: ubi9/ubi:latest
      image: "$(params.IMAGE_URL)@$(params.IMAGE_DIGEST)"

      script: |
        cd examples && terraform init

