apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-tf-syntax

spec:
  params:
    - name: IMAGE_URL
      type: string
    - name: IMAGE_DIGEST
      type: string

  steps:
    - name: check-tf-syntax
      image: "$(params.IMAGE_URL)@$(params.IMAGE_DIGEST)"
      script: |
        cd examples && terraform init
