apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-tf-syntax

spec:
  params:
    - name: IMAGE_URL
      type: string
    - name: IMAGE_DIGEST
      type: string

  steps:
    - name: check-tf-syntax
      image: "$(params.IMAGE_URL)@$(params.IMAGE_DIGEST)"
      script: |
        set -e
        cd examples/rosa-classic-with-unmanaged-oidc
        echo "Init..." && terraform init
        echo "Validate..." && terraform validate
        echo "Fmt..." && terraform fmt
        echo "Plan..." && terraform plan

